name: RentzMovil
description: "Con Rentz, renta sin estrés"
publish_to: 'none'
version: 1.0.0+12

environment:
  sdk: ^3.6.1

dependencies:
  animated_text_kit: ^4.2.2
  cached_network_image: ^3.3.0
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.1.0
  http: ^1.1.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  lottie: ^3.3.1
  path: ^1.8.3
  provider: ^6.1.2
  shimmer: ^3.0.0
  shared_preferences: ^2.2.0
  smooth_page_indicator: ^1.1.0
  sqflite: ^2.3.0
  url_launcher: ^6.2.1
  webview_flutter: ^4.4.2
  webview_flutter_android: ^4.3.3
  webview_flutter_wkwebview: ^3.9.4
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.4
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/